print("------------------------------------------------------------------------------------")
print()
print("hello, what's your name?")
print()
name = input()
print("------------------------------------------------------------------------------------")
print()
print("hello, " + name)
print("my name is AI.PROTOTYPE_385. this is the first version, but soon I will become a smart AI calculator.")
print("(if you want, you can try a version that ChatGPT made — this is what the creator wants to make.)")
