print("------------------------------------------------------------------------------------")
print()
print("hello, whats your name?")
print()
name=input()
print("------------------------------------------------------------------------------------")
print()
print("hello,",name)
print()
print("------------------------------------------------------------------------------------")
print()
print("(ask him whats his name)")
print()
name=input()
print()
print("------------------------------------------------------------------------------------")
print()
print("my name is AI.PROTOTYPE_385. this is the first version, but soon i will become an smart AI calculator, (if you want you can try an version that chatGPT made, (this is what the creator want to make).")
